DROP TABLE IF EXISTS ATTENDANCE;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS ACCOUNT_TEAM;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS TEAM;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS MATCH;
DROP TABLE IF EXISTS FILE;

CREATE TABLE ACCOUNT (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(255),
    lastName VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    phone VARCHAR(255),
    birthday DATE
);

CREATE TABLE TEAM (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    city VARCHAR(255),
    sportType VARCHAR(255)
);

CREATE TABLE ACCOUNT_TEAM (
    account_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    PRIMARY KEY (account_id, team_id),
    FOREIGN KEY (account_id) REFERENCES ACCOUNT(id),
    FOREIGN KEY (team_id) REFERENCES TEAM(id)
);

CREATE TABLE ROLE (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    roleType VARCHAR(255),
    account_id BIGINT,
    FOREIGN KEY (account_id) REFERENCES ACCOUNT(id)
);

CREATE TABLE EVENT (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    startDate DATE,
    startTime TIME,
    city VARCHAR(255),
    address VARCHAR(255),
    eventType VARCHAR(255),
    team_id BIGINT,
    FOREIGN KEY (team_id) REFERENCES TEAM(id)
);

CREATE TABLE MATCH (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    startDate DATE,
    startTime TIME,
    city VARCHAR(255),
    address VARCHAR(255),
    teamScore INT,
    opponentName VARCHAR(255),
    opponentPhone VARCHAR(255),
    opponentScore INT,
    team_id BIGINT,
    FOREIGN KEY (team_id) REFERENCES TEAM(id)
);

CREATE TABLE ATTENDANCE (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    statusType VARCHAR(255),
    account_id BIGINT,
    event_id BIGINT,
    match_id BIGINT,
    FOREIGN KEY (account_id) REFERENCES ACCOUNT(id),
    FOREIGN KEY (event_id) REFERENCES EVENT(id),
    FOREIGN KEY (match_id) REFERENCES MATCH(id)
);

CREATE TABLE FILE (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    uploadDate DATE,
    type VARCHAR(31)
);
